### ISSUE TITLE
Remove `let`

### ISSUE THREAD

**Issue by dimitrilw** [dbusteed/mojolings#1]
As of Mojo v24.2 (2024-03-28) [changelog](https://docs.modular.com/mojo/changelog#-changed-or-removed):

> let declarations now produce a compile time error instead of a warning, our next step in [removing let declarations](https://github.com/modularml/mojo/blob/main/proposals/remove-let-decls.md). The compiler still recognizes the let keyword for now in order to produce a good error message, but that will be removed in subsequent releases.

It appears that the `let` keyword will soon be completely removed from Mojo.

I will gladly make edits to update the demo files & solutions when I have time. Please respond to this issue so I know that the repo is still active.

**Comment by dbusteed** [comment]
Thanks @dimitrilw! The repo is active, and all contributions / fixes are still welcome!

I've been caught up in a few other things recently, so I'll try to update the project to use the latest version of Mojo if you don't beat me to it.

**Comment by dimitrilw** [comment]
Awesome! I'd like to help the repo keep growing. I enjoyed Rustlings and think other will enjoy Mojolings, too. I believe that I will have time to tackle this issue today. ...forking repo now.

**Comment by dimitrilw** [comment]
PR should close this issue.
